// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQjf74SSuVwCdfqYkAJmfDxesTCiIqPqs',
    appId: '1:127656542393:web:c2d11c690f3dd514c2db68',
    messagingSenderId: '127656542393',
    projectId: 'bmicalculator-da7ef',
    authDomain: 'bmicalculator-da7ef.firebaseapp.com',
    storageBucket: 'bmicalculator-da7ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1OW_0HxrHMEy5RYfP1nAsb4wDoVXWjlw',
    appId: '1:127656542393:android:3b1660e23b42ae4dc2db68',
    messagingSenderId: '127656542393',
    projectId: 'bmicalculator-da7ef',
    storageBucket: 'bmicalculator-da7ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4EXF3NOwk4qrGJiynfrF40VymBMJh3kg',
    appId: '1:127656542393:ios:41a03e0dfea5aa42c2db68',
    messagingSenderId: '127656542393',
    projectId: 'bmicalculator-da7ef',
    storageBucket: 'bmicalculator-da7ef.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4EXF3NOwk4qrGJiynfrF40VymBMJh3kg',
    appId: '1:127656542393:ios:98862f66ff499f1ec2db68',
    messagingSenderId: '127656542393',
    projectId: 'bmicalculator-da7ef',
    storageBucket: 'bmicalculator-da7ef.appspot.com',
    iosBundleId: 'com.example.bmi.RunnerTests',
  );
}
